### ISSUE TITLE
Phrase-seq-16 suggestion

### ISSUE THREAD

**Issue by AScustomWorks** [MarcBoule/ImpromptuModular#1]
Hi, I have a suggestion/request if possible, for your Phrase-seq-16 module:

CV input to control the SEQ# changes (when SEQ mode is enabled) with another sequence
(with the cv input rescaled from 0 to 10v, to your selection parameter 0-15?).

Nice work with all your modules btw. ;)

**Comment by MarcBoule** [comment]
Hi Alfredo, thank you very much for the suggestion! Funny you should mention this, since it was also raised by NaySeven on the french Rack facebook group earlier today, and I was actually working on it now and scratching my brain to see how to implement it. You are very observant, since if my SEQ# CV is enabled for both SEQ and SONG mode, then switching from one mode to the other would "corrupt" a SEQ number in the other mode as it would take effect immediately. Your comment thus gives me the cue that the CV should work only in SEQ more, and the problem is solved. 

If I may ask for your opinion on another issue I am mulling over: since I'm also adding CVs for left and right cursors, and adding the usual Fwd, Rev, Ping-Pong, RandomWalk, Random playback modes, I am considering removing the rotate and transpose buttons as they are probably not super useful, and I don't want to create a beast of a module. Since the module is not intended for live performance, I'm also removing PASTE-SYNC. If ever you think these are worthy functionalities to keep, please let me know.

The next version will have the SEQ# CV :-) Thanks again for the feedback!

P.S. I'm honored by your compliment! I've admired your aesthetics and design, which in general are not easy to do, and so I very much appreciate the comment.

**Comment by AScustomWorks** [comment]
I'm just acknowledging that you stepped in with the right foot, and in a big way ;)

This module is based on Stepper Acid module, right? If so, Nigel The Art of Sound may be able to provide great feedback, if I remember correctly he owns one of those.

Meanwhile, have you played with a x0xb0x with sokkos firmware installed?
It has the rotate and transpose functions, and they may be useful to create variations of a pattern as you can save the changes to another slot on the fly, but probably almost everyone's workflow would be to edit pattern by pattern and tweaking just the frequency and resonance of the vco when playing hehe. 

Also it has most of the the playback modes you want to include, lots of fun changing those in real time, so, perhaps a cv input to control that too?

Paste-sync may go away, sounds like it would cause confusion with users, I know it was the case with me :) Maybe save it for later?

**Comment by MarcBoule** [comment]
Lots to chew on, thanks! (I'll look into sokkos, but not sure my code-fu is up to the level of integrating firmware yet :-))

Pinging @n6smith, I would love to get your feedback on the relevance/usefullness  of transpose and rotate controls.
Pinging @nay-seven, since he also suggested the SEQ knob CV and may want to see the discussion.

I indeed wanted to try and capture the main idea behind the Stepper Acid, but in a simpler way seeing as everyone hates manuals :-). I find that with real hardware that costs hundreds of $, people may be more willing to read a detailed manual, but in the world of VCV Rack, with probably now nearing on 1000 modules, people may have less patience for complex modules that require manuals. Incidentaly, when I learned about the ER101 sequencer, I was blown away (awesome module!), but immediately thought that it would probably be too much for a Rack module.

**Comment by n6smith** [comment]
FWIW, In my opinion, transpose is a useful function but it can also be handled quite easily externally via another module... Rotate on the other hand, has to be an internal function. As for its usefulness... I do, on rare occasions, utilize the Rotate functionality on a couple of my hardware sequencers but it's not an essential feature for me, compared to CV enabled Pattern/Seq Select or Random Playback features. Given a choice, I'd happily do without Rotate if that meant having other, more important to me, functionality being present.  Would I prefer both to be present? Sure... but I get that sometimes there are trade offs to be made and so again, if that was the case, my choice would be as stated earlier. 

As an aside, the two missing functions from most Sequencers currently available in VCV Rack... are Gate Probability per Step and Pitch Change Probability per Step. The recently updated version of Quad Sequencer from Aepelzens, has sort of implemented this in terms of Gate Probability but it's not controllable in terms of selecting which specific steps, the probability would affect. 

If you would like me to go into more detail as to the implementation of both those missing functions, just let me know and i will do so...as i don't want to hijack this thread at this stage :)

**Comment by n6smith** [comment]
I also think a Software version of the ER101 would not be too much for a Rack module but then I wouldn't given my nature as a non programmer!! 😀

**Comment by MarcBoule** [comment]
The ER101 would be a hell of a challenge, for me at least! If the author agreed to share their firmware, then perhaps it would help, but from scratch it would be a big endeavour, not withstanding their having to grant us permission to emulate it in Rack. One day perhaps!

Regarding the transpose/rotate, with all the comments so far, I think I will allow the module to grow by 60HP or so and fit it all in. We'll see how it looks...

I also saw the gate probability regarding the Aepelzens sequencer in your TR7, and found it intriguing. I will study this and see what can be done in Phrase-Seq-16. As usual, I'll start things simply (gate prob only for starters), and we can build as things go. Thanks again Nigel! 

P.S. Feel free to hijack any thread of mine you want! ;-)

**Comment by MarcBoule** [comment]
@n6smith Just to understand the gate probability properly, if I add probability knobs besides the gate buttons on Phrase-Seq-16 (two such knobs since there are two gate channels), it would work as follows:
* setting the probability to 1 would mean anytime the gate is active, a gate it will be output
* setting the probability to 0 would obviously mean no gate (just like when a gate is turned off)
* setting the probability to 0.5, for example, would mean that when a gate is active, it has 50% chance of being output.
If that's the idea, then I believe it can be done easily. The knob would apply its setting in real time and no memorization would be needed. If instead you want to memorize separate probabilities for each of the steps, then it may start to get a bit complicated and I'm not sure I would go there in this first revision. Which approach did you have in mind?

P.S. Technically I guess we are deviating from AS's thread, but since the issue he raised (CV for SEQ# when in SEQ mode only) will be implemented, we can continue in this interesting direction :-)

**Comment by MarcBoule** [comment]
And Pitch Change Probability per Step would work in the same way if I understand correcly. It would be the same thing as described above, except applied to the **slide** state, instead of gate 1 and 2 states. This would control the chance that a slide occurs when slide is active in a given step. Did I get that right?

**Comment by n6smith** [comment]
I was (sort of) joking about the ER101 as it would certainly be a monumental task Im sure to port without the original code.... :)

One quick suggestion however after playing with the Phrase Seq for a couple of days now...... Make the Run command CV'able.. and then you could sort of use that in place of the Rotate (As you could start/stop a sequence on a different beat or sub division of a bar) as well as being able to Start/Stop the Sequencer itself to sync with other parts of a patch or simply to have it only play for certain periods of time. 

The Gate probability in the Quad, isn't the sort of functionality that is most useful as it isnt controllable except in a very random way. 

The basic implementation for 'real' Probability per Step would be  1) The probability (0 to 100%) of any given step producing a gate/being muted and 2) Which specific steps this would affect.  

Pitch Probability per Step would be a little more complicated :) 1) Probability per step of it occurring or not.. 2) Amount of Pitch Change on a per Step basis (One step might change between 0  and 5 semitones and another step by only 0 - 3 semitones with the option to make the possible change a fixed amount too.. i.e.  just 2 semitones or nothing.)

Musical Pitch Probability is easier to implement I would suspect, when used with a built in Scale Quantizer as per the Xynthesizr app for the iPad... (I put up a demo video of that app in the VCV rack Facebook group.. just search for Xynthesizr to find it..) but an external Quantizer could be used to produce musical sounding changes with a bit of thought and experimentation Im sure. 

Thanks Marc... for being open to all these ideas... Much appreciated! 

Note: This doesn't mean i expect all/any of them to be implemented.. Just that i appreciate the opportunity to put them out there for consideration!

**Comment by n6smith** [comment]
Just saw your earlier post.. Hopefully my descriptions of Gate and pitch prob.. match what you are thinking :) I believe the Gate one certainly does.. not sure about Pitch....

**Comment by AScustomWorks** [comment]
Hehe, see, Nigel knows his stuff 😀 
Indeed the probability thing works like you described, and 1 knob to give probability to all the steps sounds like it would be the sensible way to go to keep things simple.

Btw. another feature that may be useful:

Right now, if you edit a working pattern, any change is saved with the patch.
Say, maybe you got a nice pattern, and want to make a variation of it but forgot to copy it to another slot, your previous pattern would be lost, so, how about a restore button to get back to the last saved pattern on that particular slot you are working?... as I'm thinking about this it sounds more and more complicated though, but maybe there's an easy way to  handle it?

Oh, and we can change the thread title, as it is becoming more interesting than one cv input, another name would fit better hehe.

**Comment by n6smith** [comment]
Pitch Change prob isnt connected with slide...

Here is a description of how I imagine it working (and is implemented in other seqs..)

On the first run of seq... all pitches could be exactly as programmed.
On the second 'loop' one or more pitches may change to a different value...
On the third 'loop' some of the pitches will revert back to their original value and some will stay at their new value and some that didnt change the last time might change this time..

These changes may be small or large depending on what was set in the degree of change parameter for each step...

This results in the possibility of a constantly evolving sequence on each 'loop' where sometimes one note may change.. or two... and other times, notes will revert back to the initial settings.. Some notes can be set to never change... some notes can be set to change more frequently than others.. and so on.. and on some loops no notes will ever change..Is that a little clearer?

**Comment by MarcBoule** [comment]
@n6smith After reading your more detailed explanation of Pitch probability, it appears I didn't quite see it the correct way, and indeed no relation to slide as you mention afterwards. I might leave that one to the side for now, but I will implement gate probability knobs for the next version (as Alfredo also mentionned, it is a simple addition).

A CV for run switch is interesting as well! I'll try to see if I can squeeze it in. Faceplate real estate is easy to enlarge in VCV Rack, but design-wise, my goal is to avoid creating a huge monster. It's crazy sometimes the modules people make: the density of knobs and jacks is mindblowing! But for myself and many designers in Rack that I admire (Leonardo - Vult, Alfreso -AS, to name just two), it has to be physically realizable in a hardware module, and you have to physically have enough room around the knobs to actually turn them with your fingers. Personal view only though, not judging others' great work that may not adhere to this philosophy.

Given this, if ever I have room for only one of the following two CV inputs, **which would be more useful in your opinion**: Run CV, or Run mode CV (fwd, rev, ping-pong, etc)?

@AScustomWorks So many ideas, I'll let your latest one sink in. It perhaps it has a relation to the Stepper Acid, which seems to have a save button.

Awesome discussion guys!

**Comment by n6smith** [comment]
"Given this, if ever I have room for only one of the following two CV inputs, which would be more useful in your opinion: Run CV, or Run mode CV (fwd, rev, ping-pong, etc)?"

Run CV for sure in my opinion...

😃

**Comment by AScustomWorks** [comment]
Run CV definitely more useful, but run mode CV would open up lots of possibilities for automated variations 😆

**Comment by n6smith** [comment]
I totally understand about putting Pitch Change probability to one side.. It is a bit of a beast to implement let alone get your head around! :)

I am somewhat spoiled because I have 16 Hardware Sequencers at my disposal here.. ranging from the Metropolis, Rene, The Acid Stepper and Time's Arrow to the Squarp Pyramid and the mighty Cirklon as well as my personal favorite software Seq, Numerology...along with several custom programmed firmwares for some of them... so sequencers are kind of my 'thing' :) hence my enthusiasm for them!

**Comment by MarcBoule** [comment]
Nice set of seqs! A real synth junkie (and a heck of a reference in the VCV Rack world if I may add ;-))

For the Run CV, I take it the recommended way is to implement behavior like the State input on Grayscale Algorrythm: i.e. trigger threshold set to 1V where each revceived trigger toggles the run state?

**Comment by MarcBoule** [comment]
Yes, I save the run state. At first the pulse matrix would not save its run state, and along with someone else on github, we asked for that to be corrected and Andrew made the fix, so it's something I make sure to implement. Cheers!

**Comment by n6smith** [comment]
Oh yes! I remember now that both you and I requested that implementation in the PM. Cool.

One last thing.. for the time being at least :) 

Does your Reset also reset Pattern and Song to 1 as well as first step of Patt? if not, that might be worth thinking about.... or some alternative means of doing that as I think I remember early this morning when I was playing, that I had to manually do so upon launch of a project as it saved the Pattern and Song position (which is good too but a simple way of reseting to Patt 1 and Song 1 would be handy, if that doesn't happen already?)

**Comment by MarcBoule** [comment]
Yes, the reset should move everything back to 1, but it is not done when relaunching a project. Upon relaunch, everything is preserved from the last time. However, if it is better that we move everything back to 1 on relaunch, no problem, I will make the change (i.e. save files will not record the positions of those various pointers, and they will simply be reset when relaunched). I'll make that change in my other two sequencers as well. Thanks!

**Comment by n6smith** [comment]
While there are pros and cons to resetting/storing the status of the Seq/Song position on saving... Overall.. in my personal experience... I think that resetting it upon load.. to 1:1 would be the most useful and the most typically needed, of the two. If that turns out not to be the case with other users.. Maybe you could make that a selectable option using the right click menu?

**Comment by MarcBoule** [comment]
Upon thinking more about it after seeing your comment, I think your approach makes the most sense. Right click would be possible, but I'm trying not to have anything in my right clicks. It's a philosophical thing again, but since real modulars don't have right clicks, I want to keep it in that spirit as much as possible. I may override this one day, but I'm trying to keep that day the further away possible!

**Comment by n6smith** [comment]
Well, for discussion purposes....  Many hardware modules do have a 'right click menu' in the sense that they use DIP switches found on the back that you use to configure the device to have different basic behaviors... :) To me, the 'right click menu' is a means of emulating the use of such DIP switches.. 

It's a point I have often made with various Devs in the past.. when talking about this subject of accuracy/simulation compared to Hardware modules.. and one Im sticking to! 😆  This doesn't mean you need agree... I'm just sharing my stubborn opinion!

**Comment by MarcBoule** [comment]
Ah, interesting. If I actually owned a real module I would have known that :-) 
It's all good Nigel, I'm learning so much from you and it's really cool to have these kinds of discussions!

**Comment by MarcBoule** [comment]
Phrase-Seq-16 was updated and will likely be in the plugin manager within the next week. Until then, if you want a build to to try it out in advance, just let me know and I'll send it via private message in Facebook. I added CV inputs for the SEQ#, the run state and the run-mode, as requested, and I also implemented the gate probabilities discussed above in the thread. Many other small changes were also done, including better visual feedback when the sequencer is running in song mode. 

Thanks to both of you for the suggestions, and if you notice or think of anything else, please don't hesitate to let me know! Here's what the new version looks like:
![image](https://user-images.githubusercontent.com/33604154/39100237-f34aab6e-4654-11e8-8758-f01d1387e44d.png)

**Comment by AScustomWorks** [comment]
I thought to ask here instead of opening a new "issue":
Could it be possible to have the slide parameter length to be equal to the length between 2 steps according to clock speed? That would replicate the tb303 slide behavior. (Maybe with a switch to change from this and the current way).

You already did a great job with this seq, the slide thing would be the icing on the cake ;)

**Comment by MarcBoule** [comment]
Sounds interesting, didn't know about the 303 slide behavior, but it does make sense, and actually fixes a "problem" I was noticing when you set the slide much longer than the length between 2 clock steps (aka clock period), it would play much to weirdly, if I can say it like that :-). I'll look into it, thanks a lot for mentioning it!

**Comment by MarcBoule** [comment]
Slide button now  proportional to clock period instead of fixed duration. Will be part of the Impromptu Modular 0.6.4 release. Thanks! (I didn't go with the switch, as I want to keep things simple)
