### ISSUE TITLE
Foundry Song Mode Bug

### ISSUE THREAD

**Issue by WafflesTheDeer** [MarcBoule/ImpromptuModular#10]
Dear Marc,

Hey, been using your stuff for a long time. I'm a big fan of it. I just updated the modules, and I can't use song mode. I read the manual, but I think nothing has changed. I could be wrong though: I haven't used song mode in a while. I'll leave a picture of what it looks like. Thanks in advance!

![Foundry](https://user-images.githubusercontent.com/62186441/76688665-4bc08800-6605-11ea-9dad-9e6157e670a8.PNG)

Sincerely,
Kevin

**Comment by MarcBoule** [comment]
Hi Kevin,

In Foundry, all the lights in the keyboard and the octave lights are not used in SONG mode, and when the sequencer is not running, none of the steps should light up because the phrase # has its own display and knob. In the PhraseSeq16/32, the phrase is selected in the steps, but not in Foundry. 

So from what I can tell from your picture, it seems normal. If you enter two sequences when in SEQ mode, then move over into SONG mode, and then set phrase 1 to play seq 1, and then phrase 2 to play seq 2, and hit run, it should work. Don't forget to press the END button when in phrase 2, to mark the end of the song.

Hope that helps, if you can't get it to work, let me know.

Cheers,

Marc

**Comment by WafflesTheDeer** [comment]
Thanks man, I was confused how to use it. Keep up the good work!

**Comment by MarcBoule** [comment]
Thanks! Have fun :-)
