### ISSUE TITLE
phrase seq-16/32

### ISSUE THREAD

**Issue by gentleclockdivider** [MarcBoule/ImpromptuModular#10]
Tied notes don't seem to work .

step 1 = note 
step 2=same note tied .
This should tie the cv / gate and should sustain the note .

**Comment by MarcBoule** [comment]
Thanks for the feedback. The CV itself is properly tied/sustained in all the testing we have done (and I have just verified it again); however, the gate can not be sustained, since the gate model used in the sequencer is that we use the clock's high pulse to send as the gate out. Thus, the clock has to go low before going high again, in order to step the sequencer, and then reaching the tied step, no gate should be emitted. This is actually consistent with what one would do when stricking a piano key for example, as during the sustain across the tied notes the note is not struck again. If your clock's high pulse is too narrow (if your clock emits 1ms triggers for example), try using Clocked and increasing the pulse width. You can also try using an ADSR with a longer release to sustain the first note. Best regards.

**Comment by gentleclockdivider** [comment]
So it's impossible to create 4 quarter notes in a 16 step sequence ?

**Comment by MarcBoule** [comment]
Not sure I follow your question completely, since the concept of quarter notes, half notes, etc., is not directly part of what the sequecer does. It is still not a fully fleged DAW environment or music sheet with which we can enter more complex and varied mucical patterns. I would say to summarize, that you must use a clock rate that matches your shortest note duration, and use tied notes to create longer notes. So if you have a pattern that is based on quater notes, send a clock signal that ticks every quater note, and then if you have a half note or a full note, simply tie the given note for two or four steps. In my TODO list, I have plans for a much more versatile sequencer in the future, but for now that is all I have.

**Comment by gentleclockdivider** [comment]
What I mean is .
The sequencer is receiving it's clock from the impromptu clock .
SImple straight forward .
In the sequencer , the pattern is 16 steps long , in order to play 4 quarter notes on 16 step pattern ...
Thus 4 quarter notes long  ,not like 16thnote +16note rest+16note rest+16note rest .

We need to join/tie  four 16 th notes ..together to get ONE long quarter note ...like the good ol tb303 :)
This is what I thought the sequencer was capable off , but apparently not

**Comment by MarcBoule** [comment]
Then if it's all quarter notes you want, then perhaps simply clocking the sequencer four times slower would do the trick. If you use a divided-by-4 output from one of the three sub-clocks in Clocked, this might do it. But I imagine you have thought of that, and/or there's something else I'm not seeing correctly.

**Comment by MarcBoule** [comment]
This will be a project then for my next sequencer. Thanks for mentioning the 303, I'll look into it. Cheers!
