### ISSUE TITLE
Hotkeys for Portable sequencer commands

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#15]
Thanks for implemented chord-key port. seq. compatibilty, so game is still changing) But for really fast transfer I think we need hotkeys. For example Stoermelder strip has Shift-C\Shift V combination so it can play the ball. So what do you think on it Marc? As you can see I'm personally not a huge fan of "menu diving")

**Comment by MarcBoule** [comment]
I hate menus as well :-)
I will look into this.

**Comment by vcvrackideas** [comment]
Thanks! And also similar request - could you add an option like "switch to the next slot after pasting a chord"? It would also improve this operation in terms of speed

**Comment by MarcBoule** [comment]
The "switch to the next slot after pasting" was added in the Portable sequence menu, it's called "Autostep after paste".

Now the last thing on my list before sending it off to the library is the shortcuts. Since there are now two types of copy/pasting (please see the end of the manual of ChordKey if you're not sure of the difference), we need to decide which type of copy/paste would get the SHIFT-C / SHIFT-V shortcut, and what/if would we use for the other type?

**Comment by vcvrackideas** [comment]
I'd go for shift c shift v for copy\paste as a chord, and shift alt c\v as a sequence

**Comment by MarcBoule** [comment]
Ok, done :-)
