### ISSUE TITLE
[comment] MIDIfile player tests

### ISSUE THREAD

**Issue by davephillips** [MarcBoule/ImpromptuModular#16]
Hi Marc ! I've been building and testing the MIDIfile player, it's coming along nicely. I have a few suggestions/questions, hopefully not too premature:

1. The track autoloop could be optional.
2. In a Type 0 file's multitrack sequence the playback waits until the longest track has played through before starting all the tracks looping again. Is that the expected behavior ?
3. Given the extra space in the module's GUI I suspect you may have already considered this: An info panel for the loaded file.

Cool work, Marc. I'll keep checking it out and will be happy to test any features you add.

**Comment by MarcBoule** [comment]
Hi Dave! Thanks for dropping by. Not too premature, and it's actually quite neat to be able to discuss the module even though it is not finished. In essence, the module uses the code from Andrew's MIDI-4, but instead of reading a midi device, it uses an open source midifile parser, and simply sends that to the Code MIDI-4 code. So far, I have essentially just stitched together existing codes, but the module will now start to gain unique features, of which I'm definitely open to suggestions/discussions.

1. I did indeed plan to have a switch for making the looping optional. 
2. Yes, that is the expected behavior since internally all tracks get fused, so it will implicitly loop when the last track finished. Not sure I follow you about the type-0 though, I thought type-0 was single track, and type-1 offered multi-track possibilities.
3. I was in effect planning for some small dot matrix display or something, to show the filename of the loaded file.

I have many more ideas too for this module, some of which are:

1. Expose pedal behavior: have an option to either ignore pedal messages or convert them to gates (which is what Andrew's code does), all the while providing a CV out for the pedal state (pressed or released).
2. Perhaps have a CV out to expose the value of any program change commands (the PC value would be mapped to a 0-10V CV. This could be fun to explore, since one could use this to control parts of the patch to change sounds in real time while the midifile is playing, kind of like what a real program change does.
3. Since the polyphony is not always needed, there are many jacks that are wasted in these cases. If it's not too ugly, we could think of having configurable outputs, whereby we choose which midi channel each output responds to, and when we set two or more to the same channel, the module intrinsically understands that we want to do polyphony, and it implements the same modes as in Core MIDI-4.

Just some thoughts, not sure all of that will make it to the final version, but it's coming along! Nice to see you following too! You know at first I was planning on having 8 or 16 outputs, for many channels, but then I realized that just to implement polyphony, we need 4 outputs or so, and that the module is now unsurprisingly looking a lot like MIDI-4. So playing an entire multi-channel midi content though one instance of my midi player will likely not possible, but then again, nor is it possible with MIDI-4. I guess this is not that bad, since in modular we have fewer voices, or with many voices, they end up in different areas of the patch, such that one midi module can be placed near each voice, to separate things out a bit. 

Ok, sorry for the ramblings, but it helps organize things at least, and show where things a headed, in case you or anyone sees anything of note.

**Comment by davephillips** [comment]
Hey Marc, Just a quick note re: the MIDI file type. You're correct, and it was a Type 1 file I was testing, not Type 0. My bad, sorry about that.

**Comment by MarcBoule** [comment]
Hi Dave, 
Just to update you on this (relatively old!) thread, I have decided to remove it from my plugin, since I'm just not feeling that it has much potential in its current form. Perhaps I will revive it when Rack has evolved enough on the polyphonic cables front, but for now I rather focus on other types of modules. If ever you want to take it up as a project, just let me know and I can send you that last code I had for it. Cheers!
Marc
