### ISSUE TITLE
Phrase seq gate length

### ISSUE THREAD

**Issue by armandvedel** [MarcBoule/ImpromptuModular#18]
The TB-303 gate has 70% duty cycle. Seems like this would be a good thing to have in Phrase seq. Could you add it in adv. gate mode?

http://www.firstpr.com.au/rwi/dfish/303-slide.html

**Comment by MarcBoule** [comment]
Since the gate types are mapped to the keys of the keyboard and we have only 12 of them, adding 70% would mean removing an existing one, and since we already have 75% (the E key), I'm not sure this is worth it. Plus, since the gate types are implemented using clock resolution, all existing gate types need a clock that is a multiples of 4 or 6, and in the 70% case, we would need to add support for a clock resolution that is a multiple of 10 (since I don't use internal clock multipliers). So I guess for now it's not a change that can be done easily. Thanks for the request though! 
Best regards.
