### ISSUE TITLE
"Make master" for CLKD option

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#20]
Hi Marc! I'm still thinking on how to merge all clocked modules in VCV Rack and maybe I have anyhow decent idea) So I usually start a patch with one CLKD module and when I need more dividers I just add another clkd and make three connections and then do a reset on the first one. So I'd to suggest do these three connections and reset just in one macros like function - right click on the first module and press something like "make this instance master". So it also (if possible) can apply to other multiple instance of CLKD when for example we're loading strips that have clkd inside and then this function can make those 3 connections from a master to all of these modules at the one click. It maybe even better than expected expander ability and actually I've got an idea from Seq++ which can hook up connections from clkd and than multiply one of the divider by 4. So technically it seems that possible but who knows, interesting what do you think about it?) Cheers!

**Comment by MarcBoule** [comment]
Hi Artem, it's quite interesting, I'll have to think about all this, but it might indeed fit better than the expnder mechanism. I'm hesitant to implement clock linking through expander mechanism, because it starts getting more abstract to see what's going on behind the scenes, and it's not 100% in the modular philosophy. When I read this from Andrew:

https://community.vcvrack.com/t/advantages-of-an-expander-in-compairson-to-a-module-connected-by-cables/10282/4

it kind of convinced me that a whole bunch of hidden expander features is not fully in the spirit of the expander concept, and your autoconnect macro seems perhaps better, in the sense that the modules can be anywhere, and we still see the cables, which is a good thing I believe, given the paradigm we are aiming to replicate in a virtual modular. 

So I think I'll close issue #11 and keep this one here open, as it seems to fit better with the way I see things. Thanks for your thoughts as always!

**Comment by MarcBoule** [comment]
I have add this option to Clocked and Clkd, if you would like to try it, please let me know if you see anything wrong. Thanks for the idea, I like this better than the expander idea to link clocks :-)

**Comment by vcvrackideas** [comment]
WOOW, works awesome Marc! Huge thanks! 
Last suggestion I hope - maybe Ctrl+M to activate Connect to master function will make sense too?)
It's not even better in terms of simple modularity I think, it necessary when we add some ready to use strips synthvoices with CLKD on-board each of them, it's way handy to just connect them via this action, so nice.

**Comment by MarcBoule** [comment]
Great idea, I just added it ;-)

**Comment by Eurikon** [comment]
great idea!

**Comment by MarcBoule** [comment]
This is now released, closing.
