### ISSUE TITLE
feature request: right click to turn all gates off

### ISSUE THREAD

**Issue by joopvdl** [MarcBoule/ImpromptuModular#21]
I was trying to enter notes with a piano-style keyboard. Turns out that's working well, but if you turn off all gates first, you get the rests too. So I kindly ask for a "turn all gates off" right click option.
When you connect your keyboard to the "gate" trigger in de right extended part of the seq, it will turn on the gate every time you play a note.
Only disadvantage is you can't play notes longer than the clock length.

**Comment by MarcBoule** [comment]
Hi Joop, thanks for the suggestion, I'll think about this and see if/how to do it best. I would like to keep the right-click menu as lean as possible, and perhaps it would be best to implement as one of the cross-paste short-cuts.
https://github.com/MarcBoule/ImpromptuModular#cross-paste
Pehaps I could replace the 3rd option when cross-pasting to sequences, since one can always copy paste an unused sequence in order to initialize it. It would potentially look like this:
```
Cross paste from Song to Seq  
Type   Display   Result
4      RCV       Randomizes the CVs (pitches) of the current sequence
8      RG1       Randomizes all gates #1 of the current sequence
ALL    CGT       Turns off the gates of the steps in the current sequence
```
I'll think this over a bit though, but thanks for the suggestion!

**Comment by joopvdl** [comment]
well, it's just a suggestion..
of course, a dedicated, 4ch chord sequencer where you can play the chords
(instead of choosing from a fixed set of chords, like in the ones that are
available now) would also be interesting :)
4times cv+trig/gate in and out
step length per step
set length according to incoming pulses, not steps
easy way to create a rest
if you are interested, I would be glad to help thinking about this.
love your sequencers!

**Comment by MarcBoule** [comment]
Almost ready for the next update. 
So I went with the cross-paste idea described above. The 3rd option when cross-pasting to seq will be:
```
TG1      Toggles all gates #1 of the current sequence
```
That way it is more flexible for other potential uses, and when you start out with a fresh sequence where all gate1s are turned on, a single toggle operation like this will indeed turn them all off.

I should really do updates more often, our discussion is almost two months old :-( !
