### ISSUE TITLE
Add Ableton link ability to Clocked/Clkd

### ISSUE THREAD

**Issue by MarcBoule** [MarcBoule/ImpromptuModular#21]
From a long-time Impromptu friend:

> it would be so useful to have Link built-in to Clocked (mini). This would eliminate the use of the Stellare module when using Clocked. It also would make run/start possible by wiring this up internally using the Link V3.x start/stop capabilities.
> 
> Currently this is not possible since the stellare module has no room anymore in the design to add a run output.
> 
> I hope you can consider this or take a look at it. it would greatly enhance the already wonderful Clocked module, and make a lot of Link users happy. The Link code is opensource (sort off, i think): https://github.com/ableton/link

;-)

**Comment by vcvrackideas** [comment]
oh, good luck! hopefully you can do it strong. Stellare module is good solution but the last version cause cpu hiccups and previous is still jittering with any clock I tried before.

**Comment by Eurikon** [comment]
Thanks Marc :) 

Hi Artem) 
Sorry to hear you have bad results with the Stellare Link module.

The very 1st version from Stellare worked great at that time, the 2nd version stopped working for me.
Then this 3rd latest version is working excellent for me, no cpu problems, no sync issues.
I did hear from Steve that he can not get it to work for him either, so it differs from setup to setup i guess.

Actually i am very surprised by the very good results, hence my request to Marc for having this feature  built-in to Clocked.

The way i use it:
I run Audiobus on an iPad, the iPad is the masterclock sending out midi sync to the midi-chain and Ableton Link to the Link chain.

At this moment i sync a Roland MC707 on the midi chain.
On the software side i can sync any program (VCV Rack/ Bitwig/ Reason) to the Link sync.
I adjust the midi sync slightly on the iPad in Audiobus which has a setting for it. so that i offset the MC707 to the rest of the chain to be in "perfect" sync.

To my greatest surprise this all works very well, and adds the iPad into the game.
Let me know if you need any information about this.

Cheers,
Latif

**Comment by Eurikon** [comment]
Hi Marc, 
hope you can find some spare time for this issue.
This feature is very very welcome at this point.

**Comment by MarcBoule** [comment]
Hi Latif,
I'm quite busy with the new MindMeld module I have committed to with Steve, but it's on the radar, I just can't promise any timeframe unfortunately, sorry :-( 
Hope all is well on your end!
Cheers,
Marc

**Comment by Eurikon** [comment]
Hi Marc, all is well here, wishing you are well too 🙂 

Yeah I totally understand that you are currently swamped with the upcoming MM module!

I just thought I have to ask, must be of all the excitement I am having here due to a very successful integration of VCV and IOS workflow.

No problem I'll keep holding my breath longer heheh 😄 
Cheers my friend!

**Comment by MarcBoule** [comment]
Hi Latif and Artem, I'm sorry to say that I don't think I will be getting to this feature request, so I will unfortunately close the issue.
