### ISSUE TITLE
odd behaviour - add expander on the sequencers

### ISSUE THREAD

**Issue by Eurikon** [MarcBoule/ImpromptuModular#23]
Hi Marc,
i might be wrong  since i rarely use the feature.
But when i click on "add expander" i expected the expander to appear, and when clicking on it again i expected the expander to dissapear.
But instead clicking keeps adding more expanders :) 
Is that normal?

**Comment by MarcBoule** [comment]
Hi Latif, 
Yes, it's normal behavior. I don't think I want to getting into automating the deleting of modules though, so they have to be removed by hand. But it's an interesting thought, I'll take note of it.
Before, when the expander was actually part of the module and I would just widen it dynamically, I think that it was able to "disappear" when we would un-check the expander in the menu, but since Andrew said that expanders should be their own modules, then I just did the add behavior to create the module, but not to delete it.
Cheers!
