### ISSUE TITLE
Feature request: visualize incoming CV on Twelve-Key

### ISSUE THREAD

**Issue by smerkley** [MarcBoule/ImpromptuModular#24]
I love twelve-key (and chord-key!) and use it all the time, but one feature I would love would be for the LEDs to light up according to incoming CV on the chain input. This would allow it to be used for visualizing the output of any V/Oct CV, and I'd use it even more! Thanks for the excellent modules!

**Comment by MarcBoule** [comment]
Interesting, I'll take a look at this idea, thanks!

**Comment by MarcBoule** [comment]
I have added the _Note viewer_ option to Twelve-Key. If evey you want to test it, please let me know and I'll post a build for you in the release section. Cheers!

![image](https://user-images.githubusercontent.com/33604154/87667421-4e102b80-c738-11ea-8625-f2d8a524bf13.png)

**Comment by smerkley** [comment]
Awesome that was quick, looks exactly how I expected it to work! I'd love to test it out and I don't have a build environment set up so that'd be great!

**Comment by MarcBoule** [comment]
Cool, I've put up a Mac and Windows build here, if ever you're on Linux, let me know and I'll add that one also:
https://github.com/MarcBoule/ImpromptuModular/releases/tag/v1.1.7b

**Comment by smerkley** [comment]
After some tests there's some issues. First of all the octave buttons don't seem to work anymore, and I see that incoming CV changes the octave - which I didn't intend. I intended the CV just to be sent through and only light the LED if it matches the octave, this way you can visualize CV on any range with multiple modules linked together.

The last thing is the least important but I think the LED should stay on for the duration of the GATE input, and if you wanted you could still use the tracer option to see it longer than the gate.

**Comment by MarcBoule** [comment]
I think I misundertood your request. I made it such that we can visualize the incoming CV _with_ its octave number, so the octave display shows the octave of the CV's note (and the keys show its note). The octave buttons are indeed deactivated since there is nothing to change in that display since we are only looking at the octave value of the CV. I kind of thought TwelveKey would be just a visualization module in this mode (like FourView but with keys and oct display instead of just a single display). But I think I understand what you are describing now, I'll let that sink in a bit and see what the repercussions are with your proposal. Stay tuned :-)

**Comment by MarcBoule** [comment]
Ok, I implemented a new version which I think should be more inline with what you described. If you want to try it, I have update the builds in the latest github release.

I made it such that when a gate cable is connected it will not light the key unless the gate is high, and when no gate is connected, it keeps the key always lit. Obviously only when the cv is within the range of a given 12-Key's oct setting.

**Comment by smerkley** [comment]
Just did a quick test, it's perfect! The way the gate works is awesome too, I didn't think of using the cable connection like that.

(Kinda new to github, do I close the issue now?)

**Comment by MarcBoule** [comment]
Excellent news :-)
I don't know how others prefer things, but when they are bug reports I usually like to keep them open until the update goes through the library, such that other stumblining upon the bug and going to github to file a report will see it and not have to write a duplicate bug report. In this case, for a feature request, it can be either of us that closes it, no problem. I guess I'll do it since I'm here now. Cheers!
