### ISSUE TITLE
synth voice? 

### ISSUE THREAD

**Issue by joopvdl** [MarcBoule/ImpromptuModular#24]
I quite like the few synth voices that are available in Rack (partly triggered by the Odyssey that has entered our time/space zone) so I was looking at the other options.
Of course your semimodular synth came up, too. 
I was wondering, wouldn't it be interesting to create a synth voice without the sequencer? Maybe add a second osc, with sync and fm options?
It's very nice to have a great sounding synth that you can grab when you're creating stuff. You have a great lead sound, you think "hey, I need a bass", and you don't have the patience to patch a whole voice together. That's the idea...
Joop

**Comment by MarcBoule** [comment]
Hi Joop, I've thought of this also, and I discussed it with Xavier Belmont a while back, but we decided to skip it, but it's good to know others are thinking about this (you're not the first to mention it too!). I like to use the FM-OP by Bogaudio when I'm too lazy to patch the infamous OSC-VCA-ADSR trio, and then I just give it a bit of bite using the feedback knob, then add a filter and it's good to go. But I agree it could be useful, since in our SMS16 setup there is also an LFO, which can be very useful to add some life to the osc. I'll think about it; thanks for mentioning it!

**Comment by joopvdl** [comment]
Because of the LFO, I came up with the idea. I was using it to trigger itself.

**Comment by MarcBoule** [comment]
Hi Joop, I think I will close this one, since with Valley's Interzone that just came out, which seems to be a very nice module, I think I will keep focused on sequencers for now. Cheers!

**Comment by joopvdl** [comment]
Those sequencers are tha bomb.
