### ISSUE TITLE
CLKD bpm resets to default after restart

### ISSUE THREAD

**Issue by nnbveh** [MarcBoule/ImpromptuModular#30]
Hi. SO i've set up a template in which i use SQ1 from Nysthi modules to control the BPM. Each step set to some particular voltage corresponding to either 120, 126, 18 or 136 bpm, and i am switching between them manually, so basically use it as a collection of pre-set constant voltages. Anyways. The problem is, even if i set it to 126 bpm, after restarting CLKD goes back to 120, although i can see that SQ1 sends the voltage indeed, and CLKD itself even says it IS 126 when you hoover over the bpm knob with mouse...You can see what i mean on the screenshot.
<img width="1536" alt="Screen Shot 2020-10-25 at 10 02 06" src="https://user-images.githubusercontent.com/39271290/97100959-1c621580-16d4-11eb-8e5e-10140a8c9aa9.png">

**Comment by MarcBoule** [comment]
Hi, the tooltip over the knob shows only the setting of the knob itself, and since you have a cable connected to the BPM input, the value of the knob is not used internally and could actually be set to any value, 200 BPM for example, and the tooltip will show that value (200 BPM), all the while CLKD is really using the voltage on the BPM input to set is clock rate.
If you say that SQ1 is sending the voltage corresponding to 126 BPM but CLKD is showing 120, could you post a picture with the scope or a voltmeter showing this value please? Since I can't reproduce the problem, and I want to confirm visually that CLKD is at 120 BPM on its display all the while it's receiving a non-zero voltage on its BPM input.

**Comment by nnbveh** [comment]
You are right, i've got confused by the knob value, SQ1 doesn't send
voltage by default...i guess i need to find some other way to have pre-set
voltages table or something...
