### ISSUE TITLE
Seeking advice on proper attribution

### ISSUE THREAD

**Issue by heuermh** [MarcBoule/ImpromptuModular#31]
Hello!

I have just started a library for VCV Rack plugins (https://github.com/heuermh/LickAudio, also [GPL-3.0 License](https://github.com/heuermh/LickAudio/blob/master/LICENSE)) and wanted to make sure I gave proper attribution.

I will be using [README_SeqCode.md](README_SeqCode.md) as the starting point for a port of a simple Arduino clock/sequencer I wrote, and will most likely find inspiration in other parts of this code base (e.g. theme switching).

Thank you in advance!

**Comment by MarcBoule** [comment]
Hi, 
Thanks for reaching out. Since you will be GPL-3.0 it should be as simple as just mentioning that some parts are from ImpromptuModular, kind of like what I do for Fundamental or Rack in this license file:

https://github.com/MarcBoule/ImpromptuModular/blob/master/LICENSE-ext.md

I appreciate the mention, but if ever it ends up being just minor things like the README_SeqCode or theme switching, for me personally you don't have to bother with referencing, but if you do it's much appreciated. I'm not really well versed on licensing issues, so whatever you end up doing, as long as it's reasonable and done in good faith you'll never have any problems from me!

Cheers, and good luck with your module :-)

**Comment by heuermh** [comment]
Thank you for the quick response!  I will follow your advice.  Cheers!
