### ISSUE TITLE
Clocked 0.6.14 Gates left on.

### ISSUE THREAD

**Issue by therealkitman** [MarcBoule/ImpromptuModular#32]
Hi,  When Clocked is not running, it's 4 gates are left on. Other clocks have their gates off. See pic.
![image](https://user-images.githubusercontent.com/14888092/52543753-f7861b80-2de6-11e9-908b-6a35cca1639b.png)
Doesn't change if I hit the Reset. Please advise if this is by design or a problem.
Thanks.

**Comment by MarcBoule** [comment]
Hi, this is intentional as of 0.6.14, since it was determined that in order for first steps to not be missed on sequencers with no run inputs, or sequential switches, the clock outputs need to stay high when resetting a stopped clock. If not, when turning on the clock, any sequencer with no run inout or any sequential switch will immediately jump to the 2nd step, thus missing the first one. 

I have updated my documentation with more info if you like to know more. 
https://github.com/MarcBoule/ImpromptuModular#on-resets-clocks-and-run-states-

However, in case users really want the original behavior, I have added a switch in the right click menu of Clocked for the next version (0.6.15), and if you want to try it out, I have put preview builds in the releases section of this github repo. 

You can also see more information in these posts if you are on the VCV Rack forum:
https://community.vcvrack.com/t/impromptu-modular-announcement-thread/1694
https://community.vcvrack.com/t/impromptu-clocked-coming-changes-and-call-for-discussion/1229

**Comment by therealkitman** [comment]
Thanks Marc. All understood now. Closing issue.

**Comment by MarcBoule** [comment]
All good! Just for fun, try the Bidoo clock (tOCAnTe), you should see that its author was also probably thinking like me. If you stop that clock and press reset, the outputs go high :-) Cheers!
