### ISSUE TITLE
CLKD & CLOCKED value assign via right clicking dial doesn't work

### ISSUE THREAD

**Issue by larsfpeeters** [MarcBoule/ImpromptuModular#32]
Right-clicking the dials for CLK1, CLK2 & CLK3 and assigning a numeric value doesn't commit. BPM dial works as expected.

Tested on both Linux & Mac. Impromptu v1.1.9 & VCV v1.1.6

**Comment by MarcBoule** [comment]
Hi, thanks for reporting this, I noticed it also a few days ago when testing another module and didn't think to get to it, but you filing the issue gave me the needed nudge to fix it :-) 

Let me know if you want me to post some builds in github, since I will likely wait until a more significant update to send it to the VCV library.

Just so you know, since the knob holds one number value, I made it such that positive values correspond to multiplications, and negative values correspond to divisons, as this was the simplest way to differentiate between both. So for an _x4_ ratio, we can just type in "4", and for a _/4_ we can just type in "-4" in the knob's value.

**Comment by larsfpeeters** [comment]
Hey @MarcBoule, talk about a speedy fix! ;)

Yeah I'd love a build - I'm currently running VCV on google cloud platform and for some reason twisting knobs with a remote desktop is a pain! So the more fun I can squeeze out of my hosted VCV before my free credit expires the better!

**Comment by MarcBoule** [comment]
Excellent, builds are here:
https://github.com/MarcBoule/ImpromptuModular/releases/tag/v1.1.9b
Cheers!
