### ISSUE TITLE
melodic sequencer shows gate on/off

### ISSUE THREAD

**Issue by joopvdl** [MarcBoule/ImpromptuModular#34]
To me, it would be very handy if I could see (in phrase seq, and in foundry) if a step will output a gate, or not. Quite similar to gate sequencer, where you can see which steps will output a gate because that step is green. 
Would something like that be possible in the melodic sequencers? For instance: no gate: dark grey, gate: green, tied gate: yellow (or whatever color, of course you also have the active step, and the sequencer running light, but there are many colors in the world :)

**Comment by MarcBoule** [comment]
Indeed, I also had that thought at some point, but figured the festival of colors would be confusing and it would be hard to see the progression of the run heads while playing, but perhaps there could be a way of adding a bit of information without making it look like a xmas tree! Thanks for the ideas Joop, I'll take a look and see what could fit well.

**Comment by joopvdl** [comment]
I've been thinking about it a bit more, and think it would work best if you
choose to use different shades of grey. The current color: gate on. A bit
lighter: tied note. Even a bit lighter: gate off. That way it won't be like
a Skrillex light show, attacking you with colours.



Op za 16 feb. 2019 om 22:42 schreef Marc Boulé <notifications@github.com>:

**Comment by MarcBoule** [comment]
I'll likely attempt something like this (very light), but the shades of gray can not be changed as they represent the actuall un-lit color of the LEDs I'm using, which are dual colored LEDs (green and red). So when we apply current, only the green, red (or both) diodes can be used to change the color. You'll guess by my response that I'm trying to stay faithful to real hardware as much as possible, since a design criteria I have for my modules is that I would want to be able to build them one day :-) So changing the gray is not really possible in real hardware, but what could be possible is to replace those green-red LEDs with white LEDs (like we have in the Geodesics collection), and then use your idea with those lighter shades of the white LEDs. I really think you are on to something, since if we could "see" more of the sequence's content in the steps, it would be a big improvement.

**Comment by joopvdl** [comment]
Of course, having these in hardware would be something :) (If you can
afford hardware)(which I don't even dare to consider)

Visual orientation is very important. You know how big the difference is
between a hardware rack with 8 numbered inputs, or without numbers? It may
seem trivial, but when working, it's essential.

So I am a big fan of modules which tell me what I need to know, without
having to keep a manual open for reference. That's why I stay away from
some of the modules where I need to look up stuff again and again. And why
I spend a lot of time making Excel sheets with comparisons, etc.

I would be very happy with the solution you propose.

Op zo 17 feb. 2019 om 15:33 schreef Marc Boulé <notifications@github.com>:

**Comment by MarcBoule** [comment]
I have put a latest build in the releases section, where we now see the gate status in the step lights. Although it might be possible to also show tied steps, I wanted to keep things simple to start off. If you have any thoughts on what to change next, we can try that, but even like this I think it improves things without noticeably complxifying things.
PS16/32, SMS16, FOUNDRY were updated, as well as GS64 which now shows the contents of the steps in white when in song mode.
Any comments are welcome as always!

**Comment by joopvdl** [comment]
This is indeed very useful. You get a nice overview over the melody, and where the notes are.

**Comment by MarcBoule** [comment]
Gate visualization now in plugin manager, closing :-)
