### ISSUE TITLE
write seq long notes

### ISSUE THREAD

**Issue by joopvdl** [MarcBoule/ImpromptuModular#35]
the very practical write sequencers have no tied notes function.
So basically, all notes have the same length.
How can I program longer and shorter notes?

(this is a question, but it may turn into a feature request :)

**Comment by MarcBoule** [comment]
I would say that is a feature request :-) since that functionality is currently not part of the WriteSeqs. I'll take a look though, it may be possible to add it without changing the user interface. The gate button(s) would have three states, and pressing them in succession could perhaps toggle them between normal, full, off. This way we can have held notes (full gate) that sustain across multiple consecutive steps. Seem resonable?

**Comment by joopvdl** [comment]
sounds like a great solution!

Op za 16 feb. 2019 om 22:34 schreef Marc Boulé <notifications@github.com>:

**Comment by MarcBoule** [comment]
Done! Pressing the gate buttons in WS32 and WS64 now toggles between normal (green), held (light yellow), off. Right-clicking the gate buttons can be used to turn the gates off more quickly. 

This will be in the next release (0.6.16), but preview builds will be available in the releases section in github for testing. Thanks for the suggestion Joop!

**Comment by joopvdl** [comment]
I'm afraid the held gates still output a gate.

**Comment by MarcBoule** [comment]
I must have misunderstood your main point then. Your title mentioned long notes, and now with the new alternate gate mode, a gate can be held during an entire step to make multiple consecutive long notes. Typically, if we want a note to play across three steps, the first two would get the full (held) gate and the third one would get a normal gate. If instead you want the former tied notes behavior we originally had as default in the phrase seqs, it can still be done but it must be done manually: we set the CVs of the three steps (in my example above) to the desired note, and then just have the normal gate play in the first step, and turn the gates off in steps two and three. The ADSR will release thoughout these steps but the voice will continue to play the right note.

As for shorter notes, the duration of the (normal) gates is that of the clock signal, so all you have to do is reduce the pulse width of the clock. But this will affect all notes, so more advanced gate types would be necessary, but not sure I want to go there with these sequencers. This kind of ties in to your other discussion, where you mention:

> but there's often something in another sequencer that I would also need.

I'm also thinking about this a lot when i introduce a new feature in a seq and my instinct wants to go back to all the previous sequencers I have developped and add the feature there also. But it's a fine line to trace in the sand, because in one aspect we want to improve the tools, and this is very important, but in another aspect, this is a slippery slope. For example, a feature request now could be for the WriteSeqs to have the advanced gate modes and tied notes of the PhraseSeqs (which probably would require a new design and layout of the WriteSeqs), but after that, we could then be led to want the WriteSeqs to be able to store multiple patterns for each channel... and now all sequencers are converging to the same thing. I know you are probably not asking me to do this :-) but I'm using it as an example to show why at some point, I think the modules should also stay loyal to their original intent.

Here's another example which is really bugging me lately regarding Foundry vs PhraseSeqs. In Foundry, we have a new SEL button and a selection mode called CUST which allows us to select a custom interval of steps upon which to perform actions (turn on all gates in that interval, copy-paste, set the slide of all notes, etc). I want to do this also in the PhraseSeqs too, but it calls for a redesign and relayout of the panel, and potentially 1 or 2 HP wider, which is nontrivial. So then my reasoning was to decide that when a module is finished, even if newer cool ideas come up in their successor modules, I would not (necessarily) force those new changes into the old modules. There may be a need also for the original modules to stay like they are, so that new users have something simpler to start out with. We are so used to the PhraseSeqs, but for some they are still intimidating :-). There are so many things to look out for also, since we don't want to break patches when making improvements to existing modules either.

Anyways, that's the developper side of me resisting and argumenting, but your general point is very well taken and I agree with it. As usual, I'll let this sink in and think more about it. You know, if it wasn't for the great number of users that have made patches with Write and Phrase Seqs, I would probably clear the slate and start them over from scratch! :-)

**Comment by joopvdl** [comment]
I think your solution for write-seq works very well. I was using triggers to trigger an adsr, but when using gates this gives me what I asked for :). So thanks for that :)  Which, sort of nicely, takes us to my second point.
Which is that from a user's point, sometime what we want or think we need is, in a way, based on the fact that we want something else from the module than that what it was designed to do.

So my point was (and is): if make it clear in what field a sequencer will shine, and where it will be less suitable.  That's what I would suggest as an addition for the manual: a general section about the sequencers, and some comparison or usage suggestions.
I (and I am a quite experienced user) still find myself sometimes using a sequencer that cannot do what I need in a patch, and needing to switch, which can be a lot of work.

**Comment by MarcBoule** [comment]
Cool Joop! I made a "product comparison" table, so to speak. Here's a first draft:
https://github.com/MarcBoule/ImpromptuModular#modules-

I could have added more lines, for example to explain which copy-paste modes are available, and if the sequencer has transpose and rotate features, but I figured the table would get too big and loose its main point. 

Feel free to propose any changes to that table, or any other characteristics you think would be good to add.

**Comment by joopvdl** [comment]
Looking good so far!
I would include a short description about the philsophy behind each
sequencer.

And maybe one more category: on the fly programming (when seq is running)

Op zo 17 feb. 2019 om 20:09 schreef Marc Boulé <notifications@github.com>:

**Comment by MarcBoule** [comment]
WriteSeq long gates now in plugin manager, closing. Thanks Joop!
