### ISSUE TITLE
Portable sequence for Write-Seq

### ISSUE THREAD

**Issue by paulpiko** [MarcBoule/ImpromptuModular#35]
Hi! I recorded a sequence in Write-Seq, and wanted to paste it into another sequencer, but I don't see any portable sequence options. Could you add portable sequence to Write-Seq?

**Comment by MarcBoule** [comment]
Hi Paul, I'll take a look, cheers!

**Comment by MarcBoule** [comment]
If you want to test it, I put up a Win build here, if ever you're on Mac or Linux, just let me know and I'll add other versions. It can't be perfect, since the WriteSeqs are rather limited, but it's probably better than nothing and could perhaps save some time nonetheless.

https://github.com/MarcBoule/ImpromptuModular/releases/tag/v1.1.10b

**Comment by paulpiko** [comment]
Thanks Marc. With the new build, I was able to transfer a sequence from Write-Seq to another sequencer.
