### ISSUE TITLE
sequence selection different voltages

### ISSUE THREAD

**Issue by joopvdl** [MarcBoule/ImpromptuModular#39]
Hey,

if I try to select sequence in Phrase seq and Foundry, they will respond differently to the incoming voltage, resulting in playing different sequence numbers. Both set to the first setting, 10V.
That seems a bit impractical.

Joop

**Comment by MarcBoule** [comment]
True, I do map the full range of a given sequencer to the 0-10 range, such that in PS16, the mapping is
SEQ# 1-16 <-> 0-10 V
but in PS32 and GS64, since they allow 32 sequences, it is:
SEQ# 1-32 <-> 0-10 V
and in Foundry we have 64 sequences, so it is:
SEQ# 1-64 <-> 0-10 V

I see your point, but if someone is just using a PS16 and they map the SEQ input to a knob on an external controller, having it like this
SEQ 1-16 <-> 0-2.5 V
might be weird also since they would only use 1/4 of their knob.

I'll need to think about this more before making any changes.

**Comment by joopvdl** [comment]
You can leave it as is, of course. Just document the fact that they respond
differently. It's pretty easy to feed different voltages to different
sequencers.

**Comment by MarcBoule** [comment]
Added the mapping table from my post above to the manual in my v1 branch, so this will take effect when my 1.0 manual becomes my default manual.
