### ISSUE TITLE
Remove CC-NC clause for packaging and CC-ND questions

### ISSUE THREAD

**Issue by falkTX** [MarcBoule/ImpromptuModular#42]
Hi there.

I am interested on packaging your modules together with a special VCV build, for linux distributions.
The non-commercial clause on your artwork presents a problem though, due to linux ISOs being sellable in, for example, online stores and together in magazines.

This is a long shot but thought I would ask anyway, is there a possibility to the remove the non-commercial clause from your artwork so it can be packaged together with other tools/software?

Similarly a question about the non-derivative clause.. if your modules are included in something other than VCV but left as-is, would you consider that derivative work?

**Comment by MarcBoule** [comment]
Hi,

Your project is interesting, but unfortunately I prefer to keep the non-commercial clause for my modules. Many hours went into their making, and I would prefer them to remain non-commercial in nature.

Your second question is a bit hard to answer for me, because I'm not sure I understand how it could be possible for my modules to be left as-is while also being able to be run in something other than VCV Rack. Perhaps with a more concrete scenario I would be able to give a definitive answer.

Best regards,

Marc Boulé

**Comment by falkTX** [comment]
Thanks for your answer.

Sadly the "non-commercial" basically makes the modules "non-free" in terms of open-source licensing.
GPL does not restrict redistribution and selling of the source and its binaries.
To be able to package your modules I would have to replace all the artwork, which is too much work tbh.
My intention is not to just take what you made and sell it, but to simply package it in a different form as part of something else. Because of the GPL license on the code, any project based on it will remain open-source after all.

> Your second question is a bit hard to answer for me, because I'm not sure I understand how it could be possible for my modules to be left as-is while also being able to be run in something other than VCV Rack. Perhaps with a more concrete scenario I would be able to give a definitive answer.

This one is simple, one just needs to have an VCV API-compatible layer.

The case of Cardinal is simply a push for an open-source self-contained plugin version of VCV, but contrary to previous attempts I am not making it a fork but rather I am using the VCV code directly, wrapping things around it and replacing a few critical files as needed to make it work as a plugin.
The result is pretty much identical to standalone VCV (it is using the original VCV code after all) but it works as an audio plugin.


This NC/ND clauses are a blocker for a proper open-source project really.
But not having your modules is kinda deal-breaking too.
This makes me torn between a not proper opensource project where redistribution has very strict restrictions (non-commercial means it cannot be used in **anything** commercial at all, like being a "freebie" on an online magazine for example) vs a proper opensource project where it will only have the 100% free to use modules.

**Comment by MarcBoule** [comment]
For the ND aspect, then I think the simplest way to answer would be that if your Rack version makes it such that my repo can be used without modification, then I would not consider it a derivative work, since my repo's content would be used as is and would remain intact; but, that is my personal view for my stuff, and since my stuff uses Rack's component library, it would likely have to be the same for Andrew. If Andrew says it's ok, then I think it would work, but if not, then you would have to change all those components, which would then automatically make my modules fall into the derivatives category. Then to get around this, you would have to do many graphical/design changes so as to not appear as a derivative work, which would likely be too much work for you, as you have stated.

The NC aspect is however more problematic. That's not something I'm prepared to change, and if whatever you are doing requires a commercial license then I don't see a way forward unfortunately.

I admire your ambition to try to work through this properly and find a clean way to make your project work. Best of luck in your Cardinal journey!

**Comment by MarcBoule** [comment]
FYI: license changed to GPLv3+

**Comment by falkTX** [comment]
> FYI: license changed to GPLv3+

That is very appreciated!

Sorry to keep bumping this topic, but license issues are quite important even if boring.

To be clear, ImpromptuModular is now GPLv3+ but Geodesics continues as GPLv3-only.
What is your take on MindMeldModular? Keep it as GPLv3-only or go with GPLv3+?

**Comment by MarcBoule** [comment]
I've discussed it with the person with whom I develop MindMeldModular (different person than Geodesics), and we've made the GPLv3+ change to MindMeld (just pushed it now). Cheers!

**Comment by falkTX** [comment]
Thanks a lot! This simplifies things quite a fair bit.

PS: a related discussion about GPLv3+/only is also happening under https://github.com/zezic/ZZC/issues/86
