### ISSUE TITLE
Entered value x = x - 1

### ISSUE THREAD

**Issue by Coirt** [MarcBoule/ImpromptuModular#46]
Hi Marc, entering values into params from the menu on most of your modules is offset by 1 e.g. On Clocked entering 16 on the ratio of that clock will put the ratio to 15. You could do:

`configParam(RATIO_PARAMS + 1 + i, (34.0f - 1.0f)*-1.0f, 34.0f - 1.0f, 0.0f, strBuf, "", 0.f, 0.f, 1.f);`
https://github.com/MarcBoule/ImpromptuModular/blob/v1/src/Clocked.cpp#L355

This will offset the display value on the tooltip to 1, which will correspond to the value on the display. The default value will still be 0 internally but entering 16 will put the rate to 16.

`configParam(param, minValue, maxValue, defaultValue, string, string, baseValue, multValue, offset)`

**Comment by MarcBoule** [comment]
Hi Phil,

Your code needs two small modifications to work as you intend; I believe it should be:

`configParam(RATIO_PARAMS + 1 + i, (34.0f - 1.0f)*-1.0f, 34.0f - 1.0f, 0.0f, strBuf, "", 0.f, 1.f, -1.f);`

However, on the divisions we get an offset of 2 instead of a perfect match, and also, above x17 the mapping does not follow, as well as for x1 and x1.5, x2 and x2.5. So the change can not be general enough in my opinion for the param to be seen as a direct value. 

Thus, I'm not sure I want to make this change, since the intention of the parameter was not to specify the multiple, but an index into an internal clock ratio table. 

Thanks for the suggestion though!

Cheers,

Marc
