### ISSUE TITLE
SMS16 poly?

### ISSUE THREAD

**Issue by XtremeSounds** [MarcBoule/ImpromptuModular#48]
Any chance we can get a poly version of this with a polyphonic sequencer?  also it would be good if we could have a scale quantizer in there

**Comment by MarcBoule** [comment]
Since SMS16's audio voice is meant to be used with the onboard sequencer, I'm not sure there really is a need for a quantizer. The poly idea would require non-trivial changes that I'm unfortunately not ready to do. There are actually many interesting additions that could be made also (adding a delay would be just one), but I'm afraid that SMS16's current state is as far as I'm ready to go with this module.
