### ISSUE TITLE
Bug Report: Clocked

### ISSUE THREAD

**Issue by StillBreathingFire** [MarcBoule/ImpromptuModular#49]
Hello! Thanks for all the time you have put into your modules.

In the dropdown menu for clocked, the option for “outputs high on reset when not running” does not take when unchecked. The checkmark does not come back, but when I run it it behaves as though the checkmark is there. I have to check it and then uncheck it again to get all the “last notes played” to stop ringing in my face when I stop the clock. CLKD does NOT have this problem.

I am on Windows 10 and having this issue in VCV 2 Standalone. I have not checked it in VST.

**Comment by MarcBoule** [comment]
Unfortunately for me to investigate this I think I'll need more details of all the settings you have set in Clocked. The simplest and most effective for you would be to setup a minimal patch and save it in a state right before the mis-behaving can be produced, and then sending me the patch with exact steps to do in order to observe the faulty behavior. This may sound like a bit of a burden for you, but I've tried playing with Clocked to see the problem, and I can't see it, so to really get to the bottom of the issue, a patch with a set of steps to perform would really go a long way here to solve the issue.

You mention that CLKD does not have this probem, but could it be that your "_On Start_" and "_On Stop_" settings are different? Or that in your Clocked test, those settings are not properly set for you? Since if "_Do internal reset_" is not checked, then it is normal that the notes will keep ringing when you stop the clock and a given clock signal happens to be high (and this even with the “_Outputs high on reset when not running_” unchecked). Keep in mind that when "_Do internal reset_" is off in "_On Stop_", turning off RUN is like **pausing** the clock, so any high clock outputs are held high.

**Comment by StillBreathingFire** [comment]
I am both pleased and regretful to inform you that the issue has been found to be caused by user error. I apologize for bothering you. I had a "button" module that I use to trigger all clocks and sequencers to start/stop/reset outputting a gate instead of a trigger to the reset at the beginning of my chain. It was this holding Clocked's outputs high and not it's behavior. Forgive the mistaken report and thanks for keeping my business all in sync when I am not messing it up myself
