### ISSUE TITLE
Hotkey won't work with Radeon Relive

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#5]
Hi Marc! Maybe if you have radeon video card you can test this issue otherwise it can't be possible I think. The core of issue is that Hotkey module doesn't allow me to set hotkey that I've already set for Radeon Relive recording trigger. The reason I want to use Relive instead of OBS or something is Relive using the resources of my video card instead of CPU so in that way I'd like to reduce CPU consumption (for example camtasia takes around 15% percent of my 2500k while recording, and obs a little bit less).

**Comment by MarcBoule** [comment]
Hi Artem,
That is very strange, since I would think that it is impossible for an app to block the keys of another app when that other app has focus. Just to make sure you know, hotkey is not very powerful so you have to actually have Rack focused and have the mouse over the Hotkey module (the center part with no components for example) for it to detect the key. Also, if your hotkey has modifiers (Ctrl, Alt, Shift etc), they have to be pressed before hitting the Set button on hotkey.

- can you set the hotkey when the other app (Radeon Relive) is not running?
- can you tell me the hotkey you are trying to set so that I can try it on my side, even if I don't have Radeon Relive?
- what hotkey is displayed in the right click menu of Hotkey when you have tried to set the hotkey you want?

Thanks! Cheers,
Marc

**Comment by MarcBoule** [comment]
Closed, as per comments in issue #6
