### ISSUE TITLE
Suggestion: CLKD Expander

### ISSUE THREAD

**Issue by Dionisio765** [MarcBoule/ImpromptuModular#60]
Hi Marc

Fist of all, thank you for your amazing module´s collection.
If possible, i would like to suggest a expander module for your amazing CLKD ? The idea is to add more clock outputs.

Thank you for your time and patience.

Dionisio

**Comment by MarcBoule** [comment]
Hi Dionisio,

You can already do this now by chaining the modules, the 3 ports on the bottom are made to be connected to the 3 ports on the top. There is even a way to automatically create the cables, when a clock master is designated:

![image](https://user-images.githubusercontent.com/33604154/211586719-1ddcc851-2e2c-48bb-bbd2-fad392692774.png)

With this method, the chained clocks are supposed to be perfectly synched to the first clock. I hope that with this functionality it will be sifficient, since I will likely not be creating any expanders for more outputs (others have suggested it also, but these modules are pretty much finished for me)
Cheers, and thanks for the kind words :-)

Marc

**Comment by Dionisio765** [comment]
Hi Marc

Thank you for your reply and suggestion, i will try it.
Thank you once more.

Dionisio
