### ISSUE TITLE
Wondering who I can speak with regarding faceplate/theme contributions

### ISSUE THREAD

**Issue by JWhiteUX** [MarcBoule/ImpromptuModular#7]
Hi there,

Just downloaded your repo and started poking around the `src` files and noticed a bunch of SVGs.

Turns out I'm interested in making contributions to faceplate design, and I got tired of wrestling with Reaktor, which brought me to VCVRack, and subsequently here!

Would anyone be interested is discussing faceplate design, or module ideas?

**Comment by MarcBoule** [comment]
Hi JWhite, first off, welcome to VCV Rack! 
For module ideas, and faceplate design, and all such related discussions, I would strongly recommend the facebook groups. For general module ideas, the [VCVRack official group](https://www.facebook.com/groups/vcvrack/) would be best, and for more technical or faceplate design, perhaps the [developpers group](https://www.facebook.com/groups/2035785263299933/) would be more relevant. You'll reach a much bigger audience and be able to perhaps connect with a developper to start a collaboration. On my end, I prefer to make my panels myself (at least the Classic skins I produce), and Xavier Belmont does my Dark theme panels. Obviously, if you want to chat, I'd love to hear any suggestions, comments or insights you might have! We can chat here if you like, feel free, but the Facebook groups would also be a nice place too since more people could join the discussion. Cheers!
