### ISSUE TITLE
Clocked: Support BPM decimals

### ISSUE THREAD

**Issue by tzhf** [MarcBoule/ImpromptuModular#71]
Hi there,
Clocked is the best clock module out there, however i'm using several clock sources to make some phasing stuff à la Steve Reich and 1 BPM difference is already too much. 
So i'm constrained to use other clock modules, which are way more limited.
That'd be great if it was supported, i guess it's possible since some other clock modules have finetuning with decimal steps.

Best regards

**Comment by MarcBoule** [comment]
Hi,

It would indeed be possible, but the displays would have to be enlarged in order to make this consistent (having decimal support while not seeing the decimals in the displays would not be interesting UX-wise, in my view), and I don't think I want to get into redesigning the panels, nor the code at this point. Thanks for the kind words, I'll look forward to hearing you piece if you post it!

When I did a cover of Piano Phase in Rack a few years ago, I opted for LFOs, which allowed very precise drifting of the two square pulses:
https://www.youtube.com/watch?v=oQ1locACFNM

Cheers,

Marc

**Comment by tzhf** [comment]
Totally understand, there are a lot of workarounds. Didn't consider using LFOs, i'll test that out !

Thanks !
Théo
